package infrastructure

import (
	"context"
	"database/sql"
	"errors"

	"github.com/lib/pq"
	"github.com/nhattiendev/ewallet/internal/user/domain"
	"github.com/nhattiendev/ewallet/internal/user/infrastructure/sqlc"
)

type userRepository struct {
	db *sql.DB       // Keep the original connection in case we need it
	q  *sqlc.Queries // DB manipulation functions generated by SQLC
}

// Constructor
func NewUserRepository(db *sql.DB) domain.UserRepository {
	return &userRepository{
		db: db,
		q:  sqlc.New(db),
	}
}

func mapToUserDomain(dbUser sqlc.User) *domain.User {
	return &domain.User{
		ID:             dbUser.ID,
		FullName:       dbUser.FullName,
		Email:          dbUser.Email,
		HashedPassword: dbUser.HashedPassword,
		CreatedAt:      dbUser.CreatedAt,
	}
}

func mapToPasswordResetDomain(dbPasswordReset sqlc.PasswordReset) *domain.PasswordReset {
	return &domain.PasswordReset{
		ID: dbPasswordReset.ID,
		UserID: dbPasswordReset.UserID,
		HashedToken: dbPasswordReset.HashedToken,
		IsUsed: dbPasswordReset.IsUsed,
		ExpiresAt: dbPasswordReset.ExpiresAt,
		CreatedAt: dbPasswordReset.CreatedAt,
	}
}

func (r *userRepository) CreateUser(ctx context.Context, user *domain.User) error {
	// Prepare the parameters for the SQLC function
	arg := sqlc.CreateUserParams{
		FullName:       user.FullName,
		Email:          user.Email,
		HashedPassword: user.HashedPassword,
	}

	dbUser, err := r.q.CreateUser(ctx, arg)
	if err != nil {
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" {
			return domain.ErrEmailAlreadyExists
		}

		return err
	}

	user.ID = dbUser.ID
	user.CreatedAt = dbUser.CreatedAt

	return nil
}

func (r *userRepository) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	dbUser, err := r.q.GetUserByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, domain.ErrUserNotFound
		}
		return nil, err
	}

	return mapToUserDomain(dbUser), nil
}

func (r *userRepository) GetUserByID(ctx context.Context, id int64) (*domain.User, error) {
	dbUser, err := r.q.GetUserByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, domain.ErrUserNotFound
		}
		return nil, err
	}

	return mapToUserDomain(dbUser), nil
}

func (r *userRepository) CreatePasswordReset(ctx context.Context, passwordReset *domain.PasswordReset) error {
	arg := sqlc.CreatePasswordResetParams{
		UserID: passwordReset.UserID,
		HashedToken: passwordReset.HashedToken,
		ExpiresAt: passwordReset.ExpiresAt,
	}

	dbPasswordReset, err := r.q.CreatePasswordReset(ctx, arg)
	if err != nil {
		return err
	}

	passwordReset.ID = dbPasswordReset.ID
	passwordReset.IsUsed = dbPasswordReset.IsUsed
	passwordReset.CreatedAt = dbPasswordReset.CreatedAt

	return nil
}

func (r *userRepository) GetValidPasswordReset(ctx context.Context, hashedToken string) (*domain.PasswordReset, error) {
	dbPasswordReset, err := r.q.GetValidPasswordReset(ctx, hashedToken)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, domain.ErrInvalidResetToken
		}
		return nil, err
	}

	return mapToPasswordResetDomain(dbPasswordReset), nil
}

func (r *userRepository) MarkPasswordResetUsed(ctx context.Context, id int64) error {
	err := r.q.MarkPasswordResetUsed(ctx, id)
	if err != nil {
		return err
	}
	return nil
}

func (r *userRepository) UpdateUserPassword(ctx context.Context, userID int64, newHashedPassword string) error {
	arg := sqlc.UpdateUserPasswordParams{
		ID: userID,
		HashedPassword: newHashedPassword,
	}

	err := r.q.UpdateUserPassword(ctx, arg)
	if err != nil {
		return err
	}
	return nil
}