package infrastructure

import (
	"database/sql"
	"context"
	"errors"

	"github.com/nhattiendev/ewallet/internal/user/domain"
	"github.com/nhattiendev/ewallet/internal/user/infrastructure/sqlc"
	"github.com/lib/pq"
)

type userRepository struct {
	db *sql.DB // Keep the original connection in case we need it
	q *sqlc.Queries // DB manipulation functions generated by SQLC
}

 // Constructor
func NewUserRepository(db *sql.DB) domain.UserRepository {
	return &userRepository{
		db: db,
		q: sqlc.New(db),
	}
}

func mapToUserDomain(dbUser sqlc.User) *domain.User {
	return &domain.User{
		ID: dbUser.ID,
		FullName: dbUser.FullName,
		Email: dbUser.Email,
		HashedPassword: dbUser.HashedPassword,
		CreatedAt: dbUser.CreatedAt,
	}
}

func (r *userRepository) Create(ctx context.Context, user *domain.User) error {
	// Prepare the parameters for the SQLC function
	arg := sqlc.CreateUserParams{
		FullName: user.FullName,
		Email: user.Email,
		HashedPassword: user.HashedPassword,
	}

	dbUser, err := r.q.CreateUser(ctx, arg)
	if err != nil {
		if pqErr, ok := err.(*pq.Error); ok && pqErr.Code == "23505" {
			return domain.ErrEmailAlreadyExist
		}

		return err
	}

	user.ID = dbUser.ID
	user.CreatedAt = dbUser.CreatedAt

	return nil
}

func (r *userRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	dbUser, err := r.q.GetUserByEmail(ctx, email)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, domain.ErrUserNotFound
		}
		return nil, err
	}

	return mapToUserDomain(dbUser), nil
}

func (r *userRepository) GetByID(ctx context.Context, id int64) (*domain.User, error) {
	dbUser, err := r.q.GetUserByID(ctx, id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, domain.ErrUserNotFound
		}
		return nil, err
	}

	return mapToUserDomain(dbUser), nil
}