basePath: /
definitions:
  internal_user_delivery.forgotPasswordRequest:
    properties:
      email:
        type: string
    type: object
  internal_user_delivery.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_user_delivery.registerRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
    type: object
  internal_user_delivery.resetPasswordRequest:
    properties:
      new_password:
        type: string
      token:
        type: string
    type: object
  internal_wallet_delivery.createUserWalletRequest:
    properties:
      currency:
        type: string
    type: object
  internal_wallet_delivery.transferMoneyRequest:
    properties:
      amount:
        type: integer
      from_wallet_id:
        type: integer
      to_wallet_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Documentation for the E-Wallet Core Application.
  title: E-Wallet Core Engine API
  version: "1.0"
paths:
  /api/v1/users/forgot-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: User's email address
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user_delivery.forgotPasswordRequest'
      produces:
      - application/json
      responses: {}
      summary: Request password reset
      tags:
      - Users
  /api/v1/users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user_delivery.loginRequest'
      produces:
      - application/json
      responses: {}
      summary: Login to the system
      tags:
      - Users
  /api/v1/users/profile:
    get:
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Users
  /api/v1/users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account registration information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user_delivery.registerRequest'
      produces:
      - application/json
      responses: {}
      summary: Register a new user account
      tags:
      - Users
  /api/v1/users/reset-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Reset token and new password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_user_delivery.resetPasswordRequest'
      produces:
      - application/json
      responses: {}
      summary: Reset to a new password
      tags:
      - Users
  /api/v1/wallets:
    post:
      consumes:
      - application/json
      parameters:
      - description: Wallet creation information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_wallet_delivery.createUserWalletRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Create a new wallet for the authenticated user
      tags:
      - Wallets
  /api/v1/wallets/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Delete a user wallet
      tags:
      - Wallets
    get:
      consumes:
      - application/json
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get details of a specific wallet
      tags:
      - Wallets
  /api/v1/wallets/{id}/entries:
    get:
      consumes:
      - application/json
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      - description: Number of records to return (default 10)
        in: query
        name: limit
        type: integer
      - description: Number of records to skip (default 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get entry history (statement) for a specific wallet
      tags:
      - Wallets
  /api/v1/wallets/{id}/transfers:
    get:
      consumes:
      - application/json
      parameters:
      - description: Wallet ID
        in: path
        name: id
        required: true
        type: integer
      - description: Number of records to return (default 10)
        in: query
        name: limit
        type: integer
      - description: Number of records to skip (default 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Get transfer history for a specific wallet
      tags:
      - Wallets
  /api/v1/wallets/transfer:
    post:
      consumes:
      - application/json
      parameters:
      - description: Transfer details (FromWalletID, ToWalletID, Amount)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_wallet_delivery.transferMoneyRequest'
      produces:
      - application/json
      responses: {}
      security:
      - BearerAuth: []
      summary: Transfer money between wallets
      tags:
      - Wallets
securityDefinitions:
  BearerAuth:
    description: Type "Bearer <token>" to authenticate.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
